<?php
    return [
        'current_ay' => null,
        'current_sem' => null,
        'user_management' => 1,
        'registration' => 2,
        'enrollment' => 3,
        'academic_year_management' => 4,
        'semester_management' => 5,
        'room_management' => 6,
        'instructor_management' => 7,
        'course_management' => 8,
        'subject_management' => 9,
        'curriculum_management' => 10,
        'schedule_management' => 11,
        'activity_log' => 12,
        'assessment_management' => 13,
        'strand_management' => 14,
        'track_management' => 15,
        'student_management' => 16,
        'enrollment_management' => 17,
        'requirements_management' => 18,
        'student_schedule_management' => 19,
    ];
